config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  resources :recipe_cruds

   get 'rails_book/list'
   get 'rails_book/new'
   post 'rails_book/create'
   patch 'rails_book/update'
   get 'rails_book/list'
   get 'rails_book/show'
   get 'rails_book/edit'
   get 'rails_book/delete'
   get 'rails_book/update'
   get 'rails_book/show_subjects'
end

app/models/recipe_crud.rb
class RecipeCrud < ActiveRecord::Base
end

app/controllers/recipe_cruds_controller.rb
class RecipeCrudsController < ApplicationController
  before_action :set_recipe_crud, only: [:show, :edit, :update, :destroy]

  # GET /recipe_cruds
  # GET /recipe_cruds.json
  def index
    @recipe_cruds = RecipeCrud.all
  end

  # GET /recipe_cruds/1
  # GET /recipe_cruds/1.json
  def show
  end

  # GET /recipe_cruds/new
  def new
    @recipe_crud = RecipeCrud.new
  end

  # GET /recipe_cruds/1/edit
  def edit
  end

  # POST /recipe_cruds
  # POST /recipe_cruds.json
  def create
    @recipe_crud = RecipeCrud.new(recipe_crud_params)

    respond_to do |format|
      if @recipe_crud.save
        format.html { redirect_to @recipe_crud, notice: 'Recipe crud was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_crud }
      else
        format.html { render :new }
        format.json { render json: @recipe_crud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_cruds/1
  # PATCH/PUT /recipe_cruds/1.json
  def update
    respond_to do |format|
      if @recipe_crud.update(recipe_crud_params)
        format.html { redirect_to @recipe_crud, notice: 'Recipe crud was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_crud }
      else
        format.html { render :edit }
        format.json { render json: @recipe_crud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_cruds/1
  # DELETE /recipe_cruds/1.json
  def destroy
    @recipe_crud.destroy
    respond_to do |format|
      format.html { redirect_to recipe_cruds_url, notice: 'Recipe crud was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_crud
      @recipe_crud = RecipeCrud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_crud_params
      params.fetch(:recipe_crud, {})
    end
end

app/helpers/recipe_cruds_helper.rb
module RecipeCrudsHelper
end

app/views/recipe_cruds/_form.html.erb
<%= form_for(@recipe_crud) do |f| %>
  <% if @recipe_crud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_crud.errors.count, "error") %> prohibited this recipe_crud from being saved:</h2>

      <ul>
      <% @recipe_crud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_cruds/edit.html.erb
<h1>Editing recipe_crud</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_crud %> |
<%= link_to 'Back', recipe_cruds_path %>

app/views/recipe_cruds/index.html.erb
<h1>Listing recipe_cruds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_cruds.each do |recipe_crud| %>
      <tr>
        <td><%= link_to 'Show', recipe_crud %></td>
        <td><%= link_to 'Edit', edit_recipe_crud_path(recipe_crud) %></td>
        <td><%= link_to 'Destroy', recipe_crud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe crud', new_recipe_crud_path %>

app/views/recipe_cruds/new.html.erb
<h1>New recipe_crud</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_cruds_path %>

app/views/recipe_cruds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipe_crud_path(@recipe_crud) %> |
<%= link_to 'Back', recipe_cruds_path %>